import { StyleSheet, Platform, Dimensions, StatusBar } from "react-native";
import * as GlobalStyles from '../../GLobalStyles/GlobalStyles'
import { RFValue } from "react-native-responsive-fontsize";
const width = Dimensions.get("window").width;
const height = Dimensions.get("window").height;
import {
  responsiveFontSize,
  responsiveHeight,
  responsiveWidth,
} from "../../GLobalStyles/GlobalStyles";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    width: width,
    alignItems: "center",
    backgroundColor: GlobalStyles.Colors.generalWhite,
  },
  inputBox: {
    width: "100%",
    justifyContent: "space-between",
    height: responsiveHeight(10),
    borderWidth: 1,
    borderColor: GlobalStyles.Colors.generalWhite,
  },
  box1: {
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    height: responsiveHeight(60),
  },
  box2: {
    width: "50%",
    height: "40%",
  },
  iconBox: {
    flexDirection: "row",
    width: responsiveWidth(11),
    justifyContent: "space-between",
    paddingRight: RFValue(5),
  },
  textInputBox: {
    width: "100%",
    height: responsiveHeight(7),
    borderRadius: RFValue(15),
    backgroundColor: GlobalStyles.Colors.generalWhite,
    flexDirection: "row",
    borderWidth: 1,
    borderColor: GlobalStyles.Colors.generalWhite,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 15,
  },
  label: {
    fontSize: responsiveFontSize(2),
    marginTop: 7,
  },
  textInput: {
    width: "90%",
    paddingHorizontal: 10,
    color: GlobalStyles.Colors.generalWhite,
    height: "100%",
  },
  categories: {
    width: responsiveWidth(21),
    height: "100%",
    alignItems: "center",
    borderRadius: RFValue(10),
    marginRight: RFValue(10),
    backgroundColor: "#EDDBDB",
  },
  agent:{
    width: GlobalStyles.responsiveWidth(20),
    height: responsiveHeight(10),
    alignItems: "center",
    borderRadius: width / 2,
    marginRight: RFValue(20),
  },
  img5: {
    width: "100%",
    height: "60%",
    borderTopRightRadius: 10,
    borderTopLeftRadius: 10,
  },
  categoryText: {
    fontSize: RFValue(10),
    marginTop: RFValue(5),
    color: GlobalStyles.Colors.primaryColor,
  },
  caption: {
    width: "100%",
    height: responsiveHeight(6),
    marginBottom: RFValue(10),
    paddingHorizontal: RFValue(15),
    justifyContent: "flex-end",
  },
  captionName: { fontSize: RFValue(20), fontWeight: "bold" },
  overlay: {
    width: "100%",
    height: "100%",
    zIndex: 5000,
    position: "absolute",
    justifyContent: "space-between",
    top: 0,
    left: 0,
  },
  up: {
    width: "100%",
    height: "35%",
    flexDirection: 'row',
    paddingHorizontal: RFValue(10),
    justifyContent: "space-between",
    alignItems: 'center'
  },
  featuredNews: {
    height: responsiveHeight(40),
    marginTop: RFValue(-40),
    width: "100%",
  },
  featuredProperties1: {
    height: responsiveHeight(35),
    // paddingVertical: RFValue(10),
    marginTop: RFValue(10),
    width: "100%",
  },
  propertiesContainer1: {
    width: "48%",
    height: "100%",
    marginBottom: RFValue(15),
    marginLeft: RFValue(10),
    alignItems: "center",
    borderRadius: RFValue(10),
    justifyContent: "center",
    backgroundColor: "#F8F8F8",
  },
  imageContainer1: {
    width: "100%",
    height: "70%",
  },
  imageStyles1: {
    width: "100%",
    height: "100%",
    borderTopLeftRadius: RFValue(10),
    borderTopRightRadius: RFValue(10),
  },
  txt11: {
    width: "85%",
    height: "19%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  txt22: { fontWeight: "bold", fontSize: RFValue(7) },
  txt33: { fontSize: RFValue(5) },
  amountContainer1: {
    width: "85%",
    height: "11%",
    flexDirection: "row",
    paddingBottom: RFValue(4),
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  amount1: {
    fontSize: RFValue(5),
    fontWeight: "bold",
    color: GlobalStyles.Colors.primaryColor,
  },
  featuredNewsScrollView: {
    flexGrow: 1,
    paddingLeft: RFValue(15),
    alignItems: "center",
  },
  newsContainer: {
    width: responsiveWidth(75),
    height: "70%",
    alignItems: "center",
    borderRadius: RFValue(10),
    marginRight: RFValue(10),
    justifyContent: "center",
    // backgroundColor: "#F8F8F8",
    backgroundColor: "green",
  },
  imageContainer: {
    width: "100%",
    height: "70%",
  },
  promoted: {
    width: RFValue(80),
    justifyContent: "center",
    alignItems: "center",
    flexDirection: 'row',
    borderRadius: 10,
    backgroundColor: GlobalStyles.Colors.generalWhite,
  },
  promoted1: {
    width: '35%',
    height: '30%',
    justifyContent: "center",
    alignItems: "center",
    flexDirection: 'row',
    backgroundColor: GlobalStyles.Colors.generalWhite,
  },
  classification: {
    width: "50%",
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  imageStyles: {
    width: "100%",
    height: "100%",
    borderTopLeftRadius: RFValue(10),
    borderTopRightRadius: RFValue(10),
  },
  imageStyles1: {
    width: "100%",
    height: "100%",
  },
  txt1: {
    width: "100%",
    height: "33%",
    flexDirection: "row",
    paddingHorizontal: RFValue(10),
    justifyContent: "space-between",
    alignItems: "center",
  },
  txt2: { fontWeight: "bold", textAlign: 'left', fontSize: RFValue(10), marginBottom: 3 },
  txt3: { fontSize: RFValue(10),  marginBottom: 3,  },
  amountContainer: {
    width: "100%",
    height: "13%",
    paddingHorizontal: RFValue(20),
    alignItems: "flex-end",
  },
  amount: {
    fontSize: RFValue(20),
    fontWeight: "bold",
    color: GlobalStyles.Colors.primaryColor,
  },
  popularProperties: {
    height: responsiveHeight(55),
    marginTop: RFValue(10),
    paddingHorizontal: RFValue(15),
    width: "100%",
  },
  Networkbar: {
    width: width,
    justifyContent: "center",
    alignItems: "center",
  },
  submit: {
    width: "100%",
    alignItems: "center",
    paddingHorizontal: 20,
    justifyContent: "space-between",
  },
  buttonText: {
    marginRight: RFValue(5),
    fontSize: RFValue(12),
    color: GlobalStyles.Colors.generalWhite,
  },
  button: {
    width: responsiveWidth(60),
    height: responsiveHeight(5),
    marginTop: RFValue(20),
    borderRadius: RFValue(10),
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    backgroundColor: GlobalStyles.Colors.primaryColor,
  },
  agents: {
    width: responsiveWidth(12),
    height: responsiveWidth(12),
    alignItems: "center",
    borderRadius: RFValue(22),
    marginRight: RFValue(10),
    justifyContent: "center",
    backgroundColor: "#EDDBDB",
  },
  imageStyles1: {
    width: "100%",
    height: "100%",
    borderRadius: RFValue(22),
  },
  mainScrollView: {
    flexGrow: 1,
    width: width,
    alignItems: "center",
  },
  imageBackgroundContainer: {
    width: "100%",
    height: responsiveHeight(35),
    // borderBottomLeftRadius: 20,
    // borderBottomRightRadius: 20,
  },
  box1: {
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    height: responsiveHeight(60),
  },
  box2: {
    width: "50%",
    height: "40%",
  },
  iconBox: {
    flexDirection: "row",
    width: responsiveWidth(11),
    justifyContent: "space-between",
    paddingRight: RFValue(5),
  },
  imageBackground: {
    width: "100%",
    height: "100%",
    // borderBottomLeftRadius: 20,
    // borderBottomRightRadius: 20,
    flex: 1,
    alignItems: "center",
  },
  profileContainer: {
    width: "100%",
    height: responsiveHeight(8),
    paddingHorizontal: 15,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  imgBox: {
    height: responsiveHeight(5.5),
    width: responsiveHeight(5.5),
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: Dimensions.get("window").width / 2,
  },
  welcomeMessage: {
    fontSize: RFValue(24),
    textAlign: "center",
    fontWeight: 'bold',
    color: GlobalStyles.Colors.generalWhite,
  },
  filter: {
    color: GlobalStyles.Colors.generalWhite,
    fontSize: RFValue(24),
    textAlign: "center",
    fontWeight: "bold",
  },
  search: {
    color: GlobalStyles.Colors.generalWhite,
    fontSize: RFValue(18),
    textAlign: "center",
    marginTop: RFValue(15),
  },
});

export default styles;
